// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddToBlocklist(arg1:string,arg2:string):Promise<void>;

export function DisableAutoStart():Promise<void>;

export function EnableAutoStart():Promise<void>;

export function GetBlocklist():Promise<Array<main.BlockedApp>>;

export function GetCurrentWindow():Promise<main.WindowInfo>;

export function HideWindow():Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OnWindowChanged(arg1:any):Promise<void>;

export function RemoveFromBlocklist(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StopMonitoring():Promise<void>;
