// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToBlocklist(arg1, arg2) {
  return window['go']['main']['App']['AddToBlocklist'](arg1, arg2);
}

export function DisableAutoStart() {
  return window['go']['main']['App']['DisableAutoStart']();
}

export function EnableAutoStart() {
  return window['go']['main']['App']['EnableAutoStart']();
}

export function GetBlocklist() {
  return window['go']['main']['App']['GetBlocklist']();
}

export function GetCurrentWindow() {
  return window['go']['main']['App']['GetCurrentWindow']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function OnStartup(arg1) {
  return window['go']['main']['App']['OnStartup'](arg1);
}

export function OnWindowChanged(arg1) {
  return window['go']['main']['App']['OnWindowChanged'](arg1);
}

export function RemoveFromBlocklist(arg1) {
  return window['go']['main']['App']['RemoveFromBlocklist'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
